language: node_js
node_js: 0.1

before_script:
  - npm isntall se-interpreter

script:
- se-interpreter Sample/interpreter.json

addons:
  sauce_connect: true

env:
  global:
  - SAUCE_USERNAME: testyantra1
  - SAUCE_ACCESS_KEY: f1d4535f-7c99-4826-9c4b-27d05f7a4fdf

notifications:
  email:
    recipients:
      - rethesh.ks@testyantra.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

cache:
  directories:
  - node_modules